FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    openssl ca-certificates procps \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

EXPOSE 4006
CMD ["npm", "run", "start:dev"]
